### ISSUE TITLE
HEADERS compression: dynamic table

### ISSUE THREAD

**Issue by cmebarrow** [k3po/specification.http2#14]
See src/test/java/org/kaazing/specification/http2/headers/ProcessHeadersIT.java

[HEADERS](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-6.2)  specifies how to process and HTTP2 HEADERS frame, and [Header Compression and Decompression](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-4.3) talks about how to decompress the HEADERS frame. Tests need to be added for headers decompression using headers added to the dynamic table.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#164
