### ISSUE TITLE
HTTP headers tests -- static table for compression context

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.http2#3]
See src/test/java/org/kaazing/specification/http2/headers/ProcessHeadersIT.java

[HEADERS](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-6.2) specifies how to process and HTTP2 HEADERS frame, and [Header Compression and Decompression](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-4.3) talks about how to decompress the HEADERS frame.  The series of tests for HEADERS frames, including the decompression algorithm, needs to be implemented.

**Comment by krismcqueen** [comment]
For this section of the spec, the SETTINGS that relate to HEADERS are

 - SETTINGS_HEADER_TABLE_SIZE
 - SETTINGS_MAX_HEADER_LIST_SIZE

These settings need to be used in some of the tests.

**Comment by cmebarrow** [comment]
This issue is now only covering HEADERS frames using static compression table, with commonly used headers.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#172
