### ISSUE TITLE
DATA frames

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.http2#4]
The [DATA](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-6.1) section of the HTTP2 spec discusses processing DATA frames.  These tests need to be implemented for the following cases:

 - single data frame (simple case)
 - single stream / multiple data frames for single "response"
 - multiple streams containing data frames
 - PUSH_PROMISE frame followed by DATA pushed from server to client
 - negative tests for closed stream, bad stream ID, bad padding, etc.

**Comment by krismcqueen** [comment]
The SETTINGS_ENABLE_PUSH setting controls whether server push is allowed and should be used in at least one positive test and one negative test.

The SETTINGS_MAX_CONCURRENT_STREAMS setting controls how many streams can be created and should be used in at least one positive test and one negative test.

The SETTINGS_MAX_FRAME_SIZE setting controls how large a frame can be and should be used in at least one positive and one negative test.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#171
