### ISSUE TITLE
PING frame

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.http2#5]
The [PING](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-6.7) section of the HTTP2 spec details a PING frame that can be used at the application layer (suggested uses are round-trip timing or keep-alive, though no formal semantics are tied to the use of the frame).  The tests for processing/acknowledging this frame need to be implemented.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#170
