### ISSUE TITLE
HTTP 2.0 extensions

### ISSUE THREAD

**Issue by krismcqueen** [k3po/specification.http2#9]
[Extending HTTP/2](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-5.5) discussion extension frame and processing/ignoring them.  For now a simple test that handles an unknown frame type and ignores it would be sufficient to ensure proper handling of extensions.

**Comment by dpwspoon** [comment]
This issue was moved to k3po/k3po#166
